name: CI/CD Debugger
description: Debug CI/CD failures with LLMs

branding:
  icon: 'crosshair'
  color: 'purple'

inputs:
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
  ANTHROPIC_API_KEY:
    description: 'Anthropic API Key'

runs:
  using: 'composite'
  steps:
    - name: Run AI Debugging
      run: node ${GITHUB_ACTION_PATH}/dist/index.js
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ inputs.ANTHROPIC_API_KEY }}
