name: GPT Debugging Action
description: Debug CI/CD failure with GPT-4

branding:
  icon: 'crosshair'
  color: 'purple'

inputs:
  OPENAI_API_KEY:
    description: 'OpenAI Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run GPT Debugging
      run: node ${GITHUB_ACTION_PATH}/dist/index.js
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
