name: GPT Debugging Action
description: Debug CI/CD failure with GPT-4

inputs:
  openai-token:
    description: 'OpenAI Token'
    required: true

runs:
  steps:
    - name: Run assistant
      run: npm ci > '/dev/null' 2>&1 && npm run build > '/dev/null' 2>&1 && OPENAI_API_KEY=${{ inputs.openai-token }} npm run start
      shell: bash
