name: GPT Debugging Action
description: Debug CI/CD failure with GPT-4

# inputs:
#   openai-token:
#     description: 'OpenAI Token'
#     required: true
#   debug-log:
#     description: 'Debug Log'
#     required: true

# runs:
#   using: 'node20'
#   main: dist/index.js

runs:
  using: 'composite'
  steps:
    - name: Run GPT Debugging
      run: node ${GITHUB_ACTION_PATH}/dist/index.js
      shell: bash
